# Generated by Django 3.0 on 2020-04-10 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_app', '0004_product_actual_mrp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartProducts',
        ),
    ]
